python .\client.py recuperationLevel > recuperationLevel.log
python .\client.py WebRadio_TuneStation > WebRadio_TuneStation.log
python .\client.py tankLevelSecondary > tankLevelSecondary.log
python .\client.py unitTemperature > unitTemperature.log
python .\client.py lateralAcceleration > lateralAcceleration.log
python .\client.py Sound_BalanceFader > Sound_BalanceFader.log
python .\client.py MediaBrowser_Path > MediaBrowser_Path.log
python .\client.py Media_Track > Media_Track.log
python .\client.py Radio_SeekBackward > Radio_SeekBackward.log
python .\client.py WebRadio_PodcastEpisodes > WebRadio_PodcastEpisodes.log
python .\client.py temperatureRearRight > temperatureRearRight.log
python .\client.py Radio_AvailableBands > Radio_AvailableBands.log
python .\client.py WebRadio_LastListened > WebRadio_LastListened.log
python .\client.py unitVolume > unitVolume.log
python .\client.py acceleratorPosition > acceleratorPosition.log
python .\client.py Car_vehicleInformation > Car_vehicleInformation.log
python .\client.py Radio_Tuner > Radio_Tuner.log
python .\client.py MediaBrowser_SetSource > MediaBrowser_SetSource.log
python .\client.py recommendedGear > recommendedGear.log
python .\client.py temperatureRearLeft > temperatureRearLeft.log
python .\client.py ExAc_TouchToken > ExAc_TouchToken.log
python .\client.py consumptionLongTermGeneral > consumptionLongTermGeneral.log
python .\client.py Media_SetPlayMode > Media_SetPlayMode.log
python .\client.py currentConsumptionSecondary > currentConsumptionSecondary.log
python .\client.py powermeter > powermeter.log
python .\client.py tankLevelPrimary > tankLevelPrimary.log
python .\client.py Radio_SeekForward > Radio_SeekForward.log
python .\client.py Radio_TuneStation > Radio_TuneStation.log
python .\client.py WebRadio_CurrentStation > WebRadio_CurrentStation.log
python .\client.py WebRadio_TopStations > WebRadio_TopStations.log
python .\client.py fuelWarningSecondaryTank > fuelWarningSecondaryTank.log
python .\client.py Radio_DABServiceComponent > Radio_DABServiceComponent.log
python .\client.py Sound_SetBalanceFader > Sound_SetBalanceFader.log
python .\client.py wheelAngle > wheelAngle.log
python .\client.py accIsActive > accIsActive.log
python .\client.py Sound_Volume > Sound_Volume.log
python .\client.py currentOutputPower > currentOutputPower.log
python .\client.py ExAc_ReleaseToken > ExAc_ReleaseToken.log
python .\client.py Radio_TA > Radio_TA.log
python .\client.py currentConsumptionPrimary > currentConsumptionPrimary.log
python .\client.py suspensionProfile > suspensionProfile.log
python .\client.py Nav_StopGuidance > Nav_StopGuidance.log
python .\client.py Nav_ResolveAddress > Nav_ResolveAddress.log
python .\client.py suspensionStates > suspensionStates.log
python .\client.py batteryVoltage > batteryVoltage.log
python .\client.py dayMilage > dayMilage.log
python .\client.py ambienceLight_profiles > ambienceLight_profiles.log
python .\client.py tyrePressures > tyrePressures.log
python .\client.py Radio_SDARSPresets > Radio_SDARSPresets.log
python .\client.py Radio_AMStations > Radio_AMStations.log
python .\client.py Radio_DABEnsembles > Radio_DABEnsembles.log
python .\client.py fuelWarningPrimaryTank > fuelWarningPrimaryTank.log
python .\client.py serviceOil > serviceOil.log
python .\client.py Radio_DABServices > Radio_DABServices.log
python .\client.py Nav_ResolveLastDestination > Nav_ResolveLastDestination.log
python .\client.py Media_PlayMode > Media_PlayMode.log
python .\client.py Radio_FrequencyDecrease > Radio_FrequencyDecrease.log
python .\client.py yawRate > yawRate.log
python .\client.py driveMode > driveMode.log
python .\client.py lightState_rear > lightState_rear.log
python .\client.py maxOutputPower > maxOutputPower.log
python .\client.py Sound_Unmute > Sound_Unmute.log
python .\client.py System_Language > System_Language.log
python .\client.py displayNightDesign > displayNightDesign.log
python .\client.py shortTermConsumptionPrimary > shortTermConsumptionPrimary.log
python .\client.py serviceInspection > serviceInspection.log
python .\client.py Radio_PresetStore > Radio_PresetStore.log
python .\client.py Nav_GpxImport > Nav_GpxImport.log
python .\client.py SPI_ConnectedDevice > SPI_ConnectedDevice.log
python .\client.py EcoHMI_Score > EcoHMI_Score.log
python .\client.py Radio_ActivateBand > Radio_ActivateBand.log
python .\client.py Nav_GeoPosition > Nav_GeoPosition.log
python .\client.py Car_vehicleState > Car_vehicleState.log
python .\client.py System_HMISkin > System_HMISkin.log
python .\client.py unitTimeFormat > unitTimeFormat.log
python .\client.py MediaBrowser_Play > MediaBrowser_Play.log
python .\client.py gearboxOilTemperature > gearboxOilTemperature.log
python .\client.py ExAc_Resources > ExAc_Resources.log
python .\client.py MediaBrowser_FollowMode > MediaBrowser_FollowMode.log
python .\client.py relChargingAirPressure > relChargingAirPressure.log
python .\client.py reverseGear > reverseGear.log
python .\client.py Nav_CurrentPosition > Nav_CurrentPosition.log
python .\client.py vehicleDate > vehicleDate.log
python .\client.py System_RestrictionMode > System_RestrictionMode.log
python .\client.py acceleratorKickDown > acceleratorKickDown.log
python .\client.py Radio_SDARSStations > Radio_SDARSStations.log
python .\client.py Sound_BalanceFaderSetup > Sound_BalanceFaderSetup.log
python .\client.py Media_AvailableSources > Media_AvailableSources.log
python .\client.py Nav_GuidanceDestination > Nav_GuidanceDestination.log
python .\client.py unitDateFormat > unitDateFormat.log
python .\client.py Radio_FrequencyIncrease > Radio_FrequencyIncrease.log
python .\client.py longTermConsumptionPrimary > longTermConsumptionPrimary.log
python .\client.py outsideTemperature > outsideTemperature.log
python .\client.py clampState > clampState.log
python .\client.py shortTermConsumptionSecondary > shortTermConsumptionSecondary.log
python .\client.py Nav_StartGuidance > Nav_StartGuidance.log
python .\client.py combustionEngineDisplacement > combustionEngineDisplacement.log
python .\client.py oilTemperature > oilTemperature.log
python .\client.py Media_NextTrack > Media_NextTrack.log
python .\client.py MediaBrowser_FollowModeOn > MediaBrowser_FollowModeOn.log
python .\client.py GetImageInformationByLocator > GetImageInformationByLocator.log
python .\client.py oilLevel > oilLevel.log
python .\client.py Nav_GuidanceRemaining > Nav_GuidanceRemaining.log
python .\client.py hevacConfiguration > hevacConfiguration.log
python .\client.py Radio_FrequencyRanges > Radio_FrequencyRanges.log
python .\client.py Nav_Altitude > Nav_Altitude.log
python .\client.py Media_SwitchSource > Media_SwitchSource.log
python .\client.py Sound_Mute > Sound_Mute.log
python .\client.py tyreTemperatures > tyreTemperatures.log
python .\client.py driverIsBraking > driverIsBraking.log
python .\client.py Sound_IncreaseVolume > Sound_IncreaseVolume.log
python .\client.py ambienceLight_sets > ambienceLight_sets.log
python .\client.py engineTypes > engineTypes.log
python .\client.py gearTransmissionMode > gearTransmissionMode.log
python .\client.py Radio_StationNext > Radio_StationNext.log
python .\client.py blinkingState > blinkingState.log
python .\client.py longTermConsumptionSecondary > longTermConsumptionSecondary.log
python .\client.py vehicleTime > vehicleTime.log
python .\client.py coastingIsActive > coastingIsActive.log
python .\client.py Sound_VolumeSetup > Sound_VolumeSetup.log
python .\client.py WebRadio_Presets > WebRadio_Presets.log
python .\client.py GetImageByLocator > GetImageByLocator.log
python .\client.py seatHeater_zone1 > seatHeater_zone1.log
python .\client.py seatHeater_zone2 > seatHeater_zone2.log
python .\client.py Nav_Heading > Nav_Heading.log
python .\client.py seatHeater_zone3 > seatHeater_zone3.log
python .\client.py Media_Play > Media_Play.log
python .\client.py Car_ambienceLightColour > Car_ambienceLightColour.log
python .\client.py seatHeater_zone4 > seatHeater_zone4.log
python .\client.py hevOperationMode > hevOperationMode.log
python .\client.py Radio_DABPresets > Radio_DABPresets.log
python .\client.py Radio_TuneFrequency > Radio_TuneFrequency.log
python .\client.py combustionEngineInjection > combustionEngineInjection.log
python .\client.py Media_Pause > Media_Pause.log
python .\client.py MediaBrowser_GetList > MediaBrowser_GetList.log
python .\client.py ExAc_GetToken > ExAc_GetToken.log
python .\client.py currentGear > currentGear.log
python .\client.py Nav_GuidanceState > Nav_GuidanceState.log
python .\client.py fuelLevelState > fuelLevelState.log
python .\client.py Radio_USLPresets > Radio_USLPresets.log
python .\client.py MediaBrowser_PathCurrentTrack > MediaBrowser_PathCurrentTrack.log
python .\client.py Media_PlayerState > Media_PlayerState.log
python .\client.py Radio_StationPrevious > Radio_StationPrevious.log
python .\client.py Media_SetTrackTime > Media_SetTrackTime.log
python .\client.py totalDistance > totalDistance.log
python .\client.py tyreRequiredPressures > tyreRequiredPressures.log
python .\client.py Radio_Text > Radio_Text.log
python .\client.py cycleConsumptionPrimary > cycleConsumptionPrimary.log
python .\client.py startStopState > startStopState.log
python .\client.py MediaBrowser_FollowModeOff > MediaBrowser_FollowModeOff.log
python .\client.py Radio_USLStations > Radio_USLStations.log
python .\client.py Context_States > Context_States.log
python .\client.py tyreStates > tyreStates.log
python .\client.py unitPressure > unitPressure.log
python .\client.py System_DayNight > System_DayNight.log
python .\client.py ambienceLight_installation > ambienceLight_installation.log
python .\client.py brakePressure > brakePressure.log
python .\client.py hevacFanLevelRear > hevacFanLevelRear.log
python .\client.py maxChargingAirPressure > maxChargingAirPressure.log
python .\client.py lightState_front > lightState_front.log
python .\client.py clutch > clutch.log
python .\client.py currentTorque > currentTorque.log
python .\client.py MediaBrowser_ChangeFolder > MediaBrowser_ChangeFolder.log
python .\client.py consumptionShortTermGeneral > consumptionShortTermGeneral.log
python .\client.py engineSpeed > engineSpeed.log
python .\client.py seatVentilation_zone3 > seatVentilation_zone3.log
python .\client.py seatVentilation_zone4 > seatVentilation_zone4.log
python .\client.py Nav_LastDestinations > Nav_LastDestinations.log
python .\client.py absChargingAirPressure > absChargingAirPressure.log
python .\client.py System_UnitDistance > System_UnitDistance.log
python .\client.py Media_PreviousTrack > Media_PreviousTrack.log
python .\client.py System_activeSource > System_activeSource.log
python .\client.py parkingBrake > parkingBrake.log
python .\client.py vehicleSpeed > vehicleSpeed.log
python .\client.py Radio_PresetDelete > Radio_PresetDelete.log
python .\client.py longitudinalAcceleration > longitudinalAcceleration.log
python .\client.py doorState > doorState.log
python .\client.py Radio_FMStations > Radio_FMStations.log
python .\client.py cycleConsumptionSecondary > cycleConsumptionSecondary.log
python .\client.py System_ProximityRecognition > System_ProximityRecognition.log
python .\client.py Sound_DecreaseVolume > Sound_DecreaseVolume.log
python .\client.py coolantTemperature > coolantTemperature.log
python .\client.py MediaBrowser_ListState > MediaBrowser_ListState.log
python .\client.py Radio_AMPresets > Radio_AMPresets.log
python .\client.py ambienceLight_brightness > ambienceLight_brightness.log
python .\client.py vehicleIdenticationNumber > vehicleIdenticationNumber.log
python .\client.py Radio_FMPresets > Radio_FMPresets.log